= CV
Jack Kendall <jkendall3096@gmail.com>
:toc:

Self-taught developer with 4+ years experience in .NET. Strong interest in best
practices, automated testing and high-quality documentation.

1st class honours degree in English from the University of York (2015 - 2018).

== Experience

=== DB Cargo UK - Technical Advancement Specialist (2022 - Present)

Promotion to a new role focused on modernising a legacy solution. Some achievements:

- Upgrading 100+ intertwined .NET Framework projects to .NET Core
- Crafting a comprehensive developer documentation portal from scratch
- Transitioning a Windows server backend to cloud-native services hosted on AWS Fargate using Docker
- Moving developer teams from an on-prem TFS installation to Azure DevOps
- Implementing OpenTelemetry to reduce monthly cloud spend by 10%+
- Automating and standardising our build-test-deploy cycle across apps and environments
- Curating and leading a training and upskilling course for other developers
- Creating bespoke tooling to suit development and business needs

=== DB Cargo UK - Junior Developer (2021 - 2022)

Hands-on C# development with a large business-critical microservices platform. Technology used: ASP.NET (classic and Core), Winforms, SQL Server, MSMQ, Team Foundation Server, Git.

Gained ‘real-world’ experience debugging a distributed system; personally resolved expensive (£100k+/day) business incidents and outages. Specified, architected, implemented and deployed successful new projects with similar projected business value.

Also trained in OutSystems, a low-code platform, and the UI automation suite Leapwork.

=== Freelance copywriting (2019 - 2021)

Content creation, copywriting, editing for domestic and international clients. 

Topics included technology, marketing, science.
