= CV
Jack Kendall <jkendall3096@gmail.com>
:toc:

Skilled prose writer. Head of university publishing society. Experience with TEFL.

1st class honours degree in English from the University of York (2015 - 2018).

Conversational in French and Japanese. Studying German. Formal translation training at university.

Fluent computer user. Google Docs/Sheets, Linux, staff management/rota systems, CMS. Programming: .NET, C#, Monogame, WPF, Bash, web-scraping, game development.

== Experience

=== Freelance copywriting (2019 - Present)     

Content creation, copywriting, editing for domestic and international clients. 

Topics include technology, marketing, science. $5k+ total revenue.

=== Betfred (Assistant Manager) (2017 - 2020)    

Open/closer trust with shop keys in high-pressure retail environment. 

Trusted with £6000+ shop float, cash management, banking, marketing, creating staff rotas.

=== University of York Publishing society (2015 – 2018)        

Head of student publishing society The Looking Glass. Produced a yearly anthology of student fiction, sold for profit. 

Oversaw submissions, editing, proofreading, typesetting and design. Organised live readings and engagements with local publishers.

=== Borthwick Archives (2017)        

Documented and repaired fragile documents of historical value at university library’s archival department. 

Catalogued and preserved contemporary digital media items from the turn of the century.

=== The 20-21 Visual Arts Centre (2016)    

Volunteered at local art gallery writing exhibition labels and guidebooks for works on display. 

Self-directed work, including original research, for public consumption.

=== The Lindsey Lodge Hospice (2016)     

Volunteer work at end-of-life hospice. 

Produced and edited content for social media and in-house newsletter. Conducted interviews in-person and over the phone with general public. 

Created information brochure for Hospice donors regarding an end-of-year social night.       
