= Writing Portfolio
Jack Kendall <jkendall3096@gmail.com>
:toc:
:homepage: https://example.org

This page lists some of my recent major copywriting work. 

You can find a full listing https://www.upwork.com/freelancers/~01edd15a574b27fc7b[on my Upwork profile].

== PR Superstar

I am the main contributor to the https://prsuperstar.co.uk/blog/[PR Superstar blog], a popular resource for public relations professionals. 

I explain various facets of the field (what is crisis communications?  how should we define corporate social responsibility?) and analyze existing PR work done by others.

The posts average 2000 words each and are written for professionals and interested novices. The style of English is friendly and humorous without being colloquial.

* https://prsuperstar.co.uk/coca-cola-pr/[Coca-Cola's PR Magic: How to Stay on Top for Over a 100 Years]
* https://prsuperstar.co.uk/cipr/[The CIPR: Everything You Need to Know]
* https://prsuperstar.co.uk/fear-of-public-speaking/[How to Get Over the Fear of Public Speaking]

== Surfshark

I've written several articles for the popular VPN service https://surfshark.com/[Surfshark] about how VPNs work and co-exist with other technology.

The articles are short and written for international, non-technical readers.

== FindOnlineCourses

In late 2020, I wrote several pieces of content for FindOnlineCourses, an online e-learning aggregator.

Pieces averages 1k words in length. Topics included marketing, project management and creative arts.

https://findonlinecourses.org/creative-arts/how-to-get-a-job-as-an-illustrator/:[How to get a job as an illustrator]

https://findonlinecourses.org/project-management/revenue-operations-revops-saas/:[Why‌ ‌is‌ Revenue Operations ‌the‌ ‌fastest-growing‌ ‌job‌ ‌in‌ ‌‌SaaS‌?‌]

https://findonlinecourses.org/project-management/agile-project-management-guide/:[Agile Project Management: The Beginner’s Guide]

https://findonlinecourses.org/marketing/4-ps-of-marketing/:[What are the 4 Ps of marketing?]

== Digitalsupermarket

I wrote copy for several pages for https://digitalsupermarket.com:[Digitalsupermarket], a technology review and comparison site.

Content included reviews, topic introductions and FAQs.

https://digitalsupermarket.com/web-hosting/:[Webhosting]

https://digitalsupermarket.com/digital-banks/:[Digital banks]

https://digitalsupermarket.com/cloud-storage/:[Cloud storage]




